### ISSUE TITLE
Subsetting Google font Inter 'breaks' it

### ISSUE THREAD

**Issue by WebGuyJeff** [rafaelmardojai/webfont-kit-generator#57]
If I generate the [Inter](https://fonts.google.com/specimen/Inter) font with subsetting options Latin and Latin Extended, the produced woff2 is unable to display in the browser and uses a fallback. If I don't use subsetting the font is displayed correctly and is compressed substantially (which is nice!).

**Screenshot of settings**

![Image](https://github.com/user-attachments/assets/12cef3b8-8df5-41c6-992c-7933e956d042)

**Expected result**

![Image](https://github.com/user-attachments/assets/7cabae1b-1118-4692-b305-087de56641a9)

**Actual result**

![Image](https://github.com/user-attachments/assets/7321efcc-c7e0-4ad4-a6e3-74f55f806729)

**CSS**

```
/* inter-latin */
@font-face {
	font-family: Inter;
	font-style: normal;
	font-weight: 100 900;
	//src: local("Inter"), local("Inter-Regular"), url(/assets/fonts/inter/inter-latin.woff2) format("woff2");
	src: url(/assets/fonts/inter/inter-latin-ext.woff2) format("woff2");
	unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215;
}
/* inter-latin-ext */
@font-face {
	font-family: Inter;
	font-style: normal;
	font-weight: 100 900;
	//src: local("Inter"), local("Inter-Regular"), url(/assets/fonts/inter/inter-latin-ext.woff2) format("woff2");
	src: url(/assets/fonts/inter/inter-latin-ext.woff2) format("woff2");
	unicode-range: U+0100-024F,U+0259,U+1E00-1EFF,U+20A0-20CF,U+2C60-2C7F,U+A720-A7FF;
}

/* inter-latin italic */
@font-face {
	font-family: Inter;
	font-style: oblique 0deg 9.4deg;
	font-weight: 100 900;
	//src: local("Inter"), local("Inter-Regular"), url(/assets/fonts/inter/inter-latin.woff2) format("woff2");
	src: url(/assets/fonts/inter/inter-latin-ext.woff2) format("woff2");
	unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215;
}
/* inter-latin-ext italic */
@font-face {
	font-family: Inter;
	font-style: oblique 0deg 9.4deg;
	font-weight: 100 900;
	//src: local("Inter"), local("Inter-Regular"), url(/assets/fonts/inter/inter-latin-ext.woff2) format("woff2");
	src: url(/assets/fonts/inter/inter-latin-ext.woff2) format("woff2");
	unicode-range: U+0100-024F,U+0259,U+1E00-1EFF,U+20A0-20CF,U+2C60-2C7F,U+A720-A7FF;
}
```

**Comment by rafaelmardojai** [comment]
It seems to be working fine in the current development version, although we don't have any changes regarding font generation.

It works fine with this test:

```css
/* inter-italic-latin */
@font-face {
	font-family: "Inter";
	font-style: italic;
	font-weight: 100 900;
	font-stretch: 100%;
	src: local("Inter Italic"), local("Inter-Italic"), url(inter-italic-latin.woff2) format("woff2");
	unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215;
}
/* inter-italic-latin-ext */
@font-face {
	font-family: "Inter";
	font-style: italic;
	font-weight: 100 900;
	font-stretch: 100%;
	src: local("Inter Italic"), local("Inter-Italic"), url(inter-italic-latin-ext.woff2) format("woff2");
	unicode-range: U+0100-024F,U+0259,U+1E00-1EFF,U+20A0-20CF,U+2C60-2C7F,U+A720-A7FF;
}
/* inter-latin */
@font-face {
	font-family: "Inter";
	font-style: normal;
	font-weight: 100 900;
	font-stretch: 100%;
	src: local("Inter Regular"), local("Inter-Regular"), url(inter-latin.woff2) format("woff2");
	unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215;
}
/* inter-latin-ext */
@font-face {
	font-family: "Inter";
	font-style: normal;
	font-weight: 100 900;
	font-stretch: 100%;
	src: local("Inter Regular"), local("Inter-Regular"), url(inter-latin-ext.woff2) format("woff2");
	unicode-range: U+0100-024F,U+0259,U+1E00-1EFF,U+20A0-20CF,U+2C60-2C7F,U+A720-A7FF;
}
```

```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="inter.css">
    <style>
        body {
            font-family: "Inter";
        }

        h1 {
            font-weight: 900;
        }
    </style>

    <title>Document</title>
</head>
<body>
    <h1>Lorem ipsum</h1>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ad, obcaecati mollitia facilis cumque, illum deserunt consectetur cupiditate dolores modi numquam error expedita eligendi omnis et quae amet, repellendus quidem. Sunt.</p>
</body>
</html>
```

Full archive: [inter.zip](https://github.com/user-attachments/files/19727400/inter.zip)
